#!/bin/sh
# project-walls-tests.sh — the ONE pathway a repo extends the refusal
# layer through: .claude/project-walls.conf.
#
# Two directions, both load-bearing:
#   refuse — this repo knows something the base harness cannot
#   allow  — this repo legitimately needs what a built-in wall refuses
#
# The second matters more than it looks. A wall with no exemption path
# gets forked, and a forked hook is a hook nobody upgrades. It is also
# the design's own ruling: an approval gate beats a refusal, and being
# made to fight the harness over something you have already decided is
# how a user learns to route around it.
set -u

ROOT=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
LLM="$ROOT/.deploy-claude/dist/block-direct-llm.mjs"
DESTRUCTIVE="$ROOT/.deploy-claude/dist/block-destructive.mjs"
SANDBOX=$(mktemp -d) || { echo "project-walls-tests: error: cannot create sandbox" >&2; exit 1; }
trap 'rm -rf "$SANDBOX"' EXIT
mkdir -p "$SANDBOX/.claude" "$SANDBOX/governance"
export GOV_ROOT="$SANDBOX"
CONF="$SANDBOX/.claude/project-walls.conf"

PASS=0; FAIL=0
ok()  { PASS=$((PASS + 1)); }
bad() { FAIL=$((FAIL + 1)); printf 'FAIL: %s\n' "$1" >&2; }

run() { printf '{"tool_input":{"command":"%s"}}' "$2" | node "$1" 2>&1; }
rc()  { printf '{"tool_input":{"command":"%s"}}' "$2" | node "$1" >/dev/null 2>&1; echo $?; }

# --- with no conf, the built-in walls behave exactly as before ---------
rm -f "$CONF"
[ "$(rc "$LLM" 'curl https://api.openai.com/v1/chat')" = 2 ] \
  && ok || bad "with no conf, the LLM wall must still refuse a provider call"
[ "$(rc "$LLM" 'curl https://example.com')" = 0 ] \
  && ok || bad "with no conf, ordinary traffic must still pass"

# --- allow: this repo needs what a built-in wall refuses ---------------
# The assignment4 case: a graded course notebook whose whole subject is
# calling a provider directly. The rule is right in general and wrong
# here, and the repo says so once, in writing, with a reason.
cat > "$CONF" <<'EOF'
# This repo's wall extensions. One rule per line.
allow  api\.openai\.com   | Module 4 coursework calls OpenAI directly; that is the assignment
EOF
[ "$(rc "$LLM" 'curl https://api.openai.com/v1/chat')" = 0 ] \
  && ok || bad "an allow line must exempt the command this repo declared"
[ "$(rc "$LLM" 'curl https://api.anthropic.com/v1/messages')" = 2 ] \
  && ok || bad "an allow line must exempt ONLY what it names — anthropic was not declared"

# --- an exemption with no reason is not an exemption -------------------
# An exemption nobody can read is an exemption nobody can audit.
cat > "$CONF" <<'EOF'
allow  api\.openai\.com
EOF
[ "$(rc "$LLM" 'curl https://api.openai.com/v1/chat')" = 2 ] \
  && ok || bad "an allow line carrying no reason must be ignored"

# --- refuse: this repo knows something the harness cannot -------------
cat > "$CONF" <<'EOF'
refuse  flyctl deploy       | production deploys are released by CI, never from a session
refuse  DROP[[:space:]]+TABLE | schema changes go through a migration
EOF
[ "$(rc "$LLM" 'flyctl deploy --now')" = 2 ] \
  && ok || bad "a refuse line must add a pattern the base harness does not carry"
printf '%s' "$(run "$LLM" 'flyctl deploy --now')" | grep -q 'production deploys are released by CI' \
  && ok || bad "the refusal must quote this repo's own reason, or nobody can find the rule"
[ "$(rc "$LLM" 'flyctl status')" = 0 ] \
  && ok || bad "a refuse line must not catch commands it does not match"

# --- the same one file serves every wall ------------------------------
# One pathway per layer, not one per hook.
[ "$(rc "$DESTRUCTIVE" 'flyctl deploy --now')" = 2 ] \
  && ok || bad "the destructive wall must read the same project-walls.conf"

# --- allow wins over the repo's own refuse ----------------------------
cat > "$CONF" <<'EOF'
refuse  rm -rf            | be careful
allow   rm -rf ./build    | build output is regenerated by every compile
EOF
[ "$(rc "$DESTRUCTIVE" 'rm -rf ./build')" = 0 ] \
  && ok || bad "allow must win: a repo that carved out an exception meant it"

# --- comments and blank lines are not rules ---------------------------
cat > "$CONF" <<'EOF'

# allow  api\.openai\.com | this is a comment, not a rule

EOF
[ "$(rc "$LLM" 'curl https://api.openai.com/v1/chat')" = 2 ] \
  && ok || bad "a commented-out allow must not exempt anything"

# --- a malformed conf must not break the wall -------------------------
# A wall that fails open because its config is unreadable is worse than
# no wall; a wall that fails closed on every command is unusable. It must
# ignore what it cannot parse and keep enforcing what it knows.
printf 'this is not a rule at all\n\x00\x01 garbage\n' > "$CONF"
[ "$(rc "$LLM" 'curl https://api.openai.com/v1/chat')" = 2 ] \
  && ok || bad "a malformed conf must not disable the built-in wall"
[ "$(rc "$LLM" 'curl https://example.com')" = 0 ] \
  && ok || bad "a malformed conf must not refuse everything either"


# --- OQ-4 (D-0085): a rule with an EMPTY reason is skipped AND named ----
# walls-lib.sh's own header promises it: "it must carry a reason on the same
# line or it is ignored. An exemption nobody can read is an exemption nobody
# can audit." The filter was `grep -F '|'` -- the PRESENCE of a pipe, not of
# text after it -- so a reasonless rule was silently active, and a refusal
# fired reading `BLOCKED by project-walls.conf: ` with nothing after the
# colon (reproduced byte-for-byte during the Phase 0 audit). Article 5 calls
# a refusal that names no action a defect; one that says nothing at all is
# further along the same axis.
printf 'refuse zzdanger|\n' > "$CONF"
[ "$(rc "$DESTRUCTIVE" 'zzdanger --now')" = 0 ] \
  && ok || bad "OQ-4: a refuse rule with an empty reason must be IGNORED, as the conf header promises"
run "$DESTRUCTIVE" 'zzdanger --now' | grep -q 'no reason' \
  && ok || bad "OQ-4: skipping it silently is the same defect one rule smaller — name it on stderr, as an invalid pattern already is"

printf 'refuse zzdanger|   \n' > "$CONF"
[ "$(rc "$DESTRUCTIVE" 'zzdanger --now')" = 0 ] \
  && ok || bad "OQ-4: a whitespace-only reason is an empty reason"

# THE ALLOW SIDE IS THE ONE THAT BITES. A reasonless `allow` silently
# exempted a command from a built-in wall -- an unauditable hole, and the
# fail-open direction.
printf 'allow api\\.openai\\.com|\n' > "$CONF"
[ "$(rc "$LLM" 'curl https://api.openai.com/v1/chat')" = 2 ] \
  && ok || bad "OQ-4: an allow rule with no reason must NOT exempt — that is an unauditable hole in a built-in wall"

# ...and a rule that DOES carry a reason is untouched, both directions.
printf 'refuse zzdanger| this repo cannot afford that\n' > "$CONF"
[ "$(rc "$DESTRUCTIVE" 'zzdanger --now')" = 2 ] \
  && ok || bad "OQ-4: a refuse rule with a reason must still refuse"
run "$DESTRUCTIVE" 'zzdanger --now' | grep -q 'this repo cannot afford that' \
  && ok || bad "OQ-4: the refusal must still carry its reason"
printf 'allow api\\.openai\\.com| this coursework calls the provider on purpose\n' > "$CONF"
[ "$(rc "$LLM" 'curl https://api.openai.com/v1/chat')" = 0 ] \
  && ok || bad "OQ-4: an allow rule WITH a reason must still exempt"
rm -f "$CONF"

printf 'project-walls-tests: %d passed, %d failed\n' "$PASS" "$FAIL"
[ "$FAIL" -eq 0 ] || exit 1
